### ISSUE TITLE
Could you explain the difference and intended uses of web3_client and client, im unclear on why theyre different files

### ISSUE THREAD

**Issue by kjr217** [8ball030/rysk_explorations#51]
https://github.com/8ball030/rysk_explorations/blob/baac205c826d65035bec5a40d96f0d2e4025cba9/rysk_client/web3_client.py#L426

**Comment by 8ball030** [comment]
certainly.
I was aiming to have a rysk_client, which would hold the abstracts such as;
A) pnl_manager
B) market_manager

In an ideal world the, the web3_client would be much better abstracted.

There is a lot of unnecessary code, and I will be cleaning this up and removing it as I address your issues.

Lmk if this clears things up or na :)
