### ISSUE TITLE
is e18 correct here or should it depend on the collateral decimals?

### ISSUE THREAD

**Issue by kjr217** [8ball030/rysk_explorations#53]
https://github.com/8ball030/rysk_explorations/blob/baac205c826d65035bec5a40d96f0d2e4025cba9/rysk_client/client.py#L373

**Comment by kjr217** [comment]
https://github.com/8ball030/rysk_explorations/blob/baac205c826d65035bec5a40d96f0d2e4025cba9/rysk_client/client.py#L386

**Comment by 8ball030** [comment]
Yes it should, this flat down wrong unfortunatetely.

**Comment by 8ball030** [comment]
Still needs an update here;
https://github.com/8ball030/rysk_explorations/blob/cc77d90fb88b47aacd3bcadf99d534b59e2970c1/rysk_client/client.py#L460C46-L460C69

**Comment by 8ball030** [comment]
https://github.com/8ball030/rysk_explorations/pull/90
