### ISSUE TITLE
bit confused as to why amount is being approved here?

### ISSUE THREAD

**Issue by kjr217** [8ball030/rysk_explorations#57]
https://github.com/8ball030/rysk_explorations/blob/baac205c826d65035bec5a40d96f0d2e4025cba9/rysk_client/client.py#L501

**Comment by 8ball030** [comment]
This is the amount in eth,

This client is currently setup to always cover calls and puts.

if we its a put, we need to make sure its collateralised, I currently do so with a bit extra, 

Strikes me that it should actually be;

```python
if rysk_option_market.is_put:
      amount_to_approve = rysk_option_market.strike # converted to usdc
else;
      collateral_asset = Collateral.WETH
      amount_to_approve = _amount


```

**Comment by 8ball030** [comment]
Check this one out;
I removed the noise from the operation factory and added in some further tests.

**Comment by 8ball030** [comment]
https://github.com/8ball030/rysk_explorations/pull/78/files
