### ISSUE TITLE
Where are you keeping teh mainnet addresses?

### ISSUE THREAD

**Issue by kjr217** [8ball030/rysk_explorations#61]
https://github.com/8ball030/rysk_explorations/blob/4ce76eb1fe795cbe7323c1b1def8d1efb0079d09/rysk_client/src/collateral.py#L12

**Comment by 8ball030** [comment]
https://github.com/8ball030/rysk_explorations/pull/73

This adds in a collateral_factory based on the chain to retrieve it.
