### ISSUE TITLE
You may as well use the otoken address here, seeing as you already use it

### ISSUE THREAD

**Issue by kjr217** [8ball030/rysk_explorations#65]
https://github.com/8ball030/rysk_explorations/blob/4ce76eb1fe795cbe7323c1b1def8d1efb0079d09/rysk_client/src/operation_factory.py#L183

**Comment by 8ball030** [comment]
What do you mean? 
Pretty sure this fails when using the otken here?

**Comment by kjr217** [comment]
you should be able to use the otoken address

**Comment by 8ball030** [comment]
https://github.com/8ball030/rysk_explorations/pull/89
